# Import Data

In [ ]:
import pandas as pd
import numpy as np

#Load Data dari Github

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/hastisf/python-data-analyst/refs/heads/master/hotel_bookings.csv")

In [37]:
df['hotel']

0         Resort Hotel
1         Resort Hotel
2         Resort Hotel
3         Resort Hotel
4         Resort Hotel
              ...
119385      City Hotel
119386      City Hotel
119387      City Hotel
119388      City Hotel
119389      City Hotel
Name: hotel, Length: 119390, dtype: object

# Data Library

In [ ]:
pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.49)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.12)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)

In [ ]:
import pandas as pd
from sqlalchemy import create_engine

In [ ]:
from urllib.parse import quote_plus

In [ ]:
username = "postgres.smavqpvlzydbrauxsxld"
password = quote_plus("5h!AkBfk3@rWBLt")
host = "aws-1-ap-southeast-1.pooler.supabase.com"
port = "6543"
database = "postgres"

DATABASE_URL = (
    f"postgresql://{username}:{password}@{host}:{port}/{database}"
)

engine = create_engine(DATABASE_URL)

In [ ]:
df.to_sql("hotel_bookings", engine, if_exists="replace", index=False)

OperationalError: (psycopg2.errors.QueryCanceled) canceling statement due to statement timeout

[SQL: INSERT INTO hotel_bookings (hotel, is_canceled, lead_time, arrival_date_year, arrival_date_month, arrival_date_week_number, arrival_date_day_of_month, stays_in_weekend_nights, stays_in_week_nights, adults, children, babies, meal, country, market_segm ... 840717 characters truncated ... , %(total_of_special_requests__999)s, %(reservation_status__999)s, %(reservation_status_date__999)s)]
[parameters: {'previous_bookings_not_canceled__0': 0, 'total_of_special_requests__0': 0, 'hotel__0': 'Resort Hotel', 'meal__0': 'HB', 'country__0': 'PRT', 'arrival_date_week_number__0': 16, 'customer_type__0': 'Transient', 'reservation_status__0': 'Canceled', 'days_in_waiting_list__0': 0, 'reservation_status_date__0': '2015-10-16', 'arrival_date_month__0': 'April', 'previous_cancellations__0': 0, 'booking_changes__0': 0, 'deposit_type__0': 'Non Refund', 'company__0': None, 'arrival_date_year__0': 2016, 'reserved_room_type__0': 'D', 'market_segment__0': 'Groups', 'is_canceled__0': 1, 'distribution_channel__0': 'Direct', 'babies__0': 0, 'required_car_parking_spaces__0': 0, 'adr__0': 76.05, 'is_repeated_guest__0': 0, 'assigned_room_type__0': 'D', 'arrival_date_day_of_month__0': 11, 'stays_in_week_nights__0': 5, 'adults__0': 2, 'children__0': 0.0, 'agent__0': 273.0, 'lead_time__0': 212, 'stays_in_weekend_nights__0': 2, 'previous_bookings_not_canceled__1': 0, 'total_of_special_requests__1': 2, 'hotel__1': 'Resort Hotel', 'meal__1': 'HB', 'country__1': 'GBR', 'arrival_date_week_number__1': 16, 'customer_type__1': 'Transient', 'reservation_status__1': 'Check-Out', 'days_in_waiting_list__1': 0, 'reservation_status_date__1': '2016-04-21', 'arrival_date_month__1': 'April', 'previous_cancellations__1': 0, 'booking_changes__1': 1, 'deposit_type__1': 'No Deposit', 'company__1': None, 'arrival_date_year__1': 2016, 'reserved_room_type__1': 'E', 'market_segment__1': 'Online TA' ... 31900 parameters truncated ... 'company__998': None, 'arrival_date_year__998': 2016, 'reserved_room_type__998': 'A', 'market_segment__998': 'Offline TA/TO', 'is_canceled__998': 0, 'distribution_channel__998': 'TA/TO', 'babies__998': 0, 'required_car_parking_spaces__998': 0, 'adr__998': 41.33, 'is_repeated_guest__998': 0, 'assigned_room_type__998': 'A', 'arrival_date_day_of_month__998': 19, 'stays_in_week_nights__998': 6, 'adults__998': 2, 'children__998': 0.0, 'agent__998': 156.0, 'lead_time__998': 274, 'stays_in_weekend_nights__998': 2, 'previous_bookings_not_canceled__999': 0, 'total_of_special_requests__999': 2, 'hotel__999': 'Resort Hotel', 'meal__999': 'HB', 'country__999': 'PRT', 'arrival_date_week_number__999': 21, 'customer_type__999': 'Transient', 'reservation_status__999': 'Canceled', 'days_in_waiting_list__999': 0, 'reservation_status_date__999': '2016-01-20', 'arrival_date_month__999': 'May', 'previous_cancellations__999': 0, 'booking_changes__999': 1, 'deposit_type__999': 'No Deposit', 'company__999': None, 'arrival_date_year__999': 2016, 'reserved_room_type__999': 'D', 'market_segment__999': 'Online TA', 'is_canceled__999': 1, 'distribution_channel__999': 'TA/TO', 'babies__999': 0, 'required_car_parking_spaces__999': 0, 'adr__999': 125.5, 'is_repeated_guest__999': 0, 'assigned_room_type__999': 'D', 'arrival_date_day_of_month__999': 19, 'stays_in_week_nights__999': 6, 'adults__999': 2, 'children__999': 1.0, 'agent__999': 240.0, 'lead_time__999': 155, 'stays_in_weekend_nights__999': 2}]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

# Info Data

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB

#Describe Data

In [ ]:
df.describe()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119386.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,103050.000000,6797.000000,119390.000000,119390.000000,119390.000000,119390.000000
mean,0.370416,104.011416,2016.156554,27.165173,15.798241,0.927599,2.500302,1.856403,0.103890,0.007949,0.031912,0.087118,0.137097,0.221124,86.693382,189.266735,2.321149,101.831122,0.062518,0.571363
std,0.482918,106.863097,0.707476,13.605138,8.780829,0.998613,1.908286,0.579261,0.398561,0.097436,0.175767,0.844336,1.497437,0.652306,110.774548,131.655015,17.594721,50.535790,0.245291,0.792798
min,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6.000000,0.000000,-6.380000,0.000000,0.000000
25%,0.000000,18.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,62.000000,0.000000,69.290000,0.000000,0.000000
50%,0.000000,69.000000,2016.000000,28.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,179.000000,0.000000,94.575000,0.000000,0.000000
75%,1.000000,160.000000,2017.000000,38.000000,23.000000,2.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,229.000000,270.000000,0.000000,126.000000,0.000000,1.000000
max,1.000000,737.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,55.000000,10.000000,10.000000,1.000000,26.000000,72.000000,21.000000,535.000000,543.000000,391.000000,5400.000000,8.000000,5.000000

# Cek Duplicate

In [ ]:
df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
119385    False
119386    False
119387    False
119388    False
119389    False
Length: 119390, dtype: bool

In [ ]:
df.duplicated().sum()

np.int64(31994)

# Hapus Duplicate

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 87396 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           87396 non-null  object
 1   is_canceled                     87396 non-null  int64
 2   lead_time                       87396 non-null  int64
 3   arrival_date_year               87396 non-null  int64
 4   arrival_date_month              87396 non-null  object
 5   arrival_date_week_number        87396 non-null  int64
 6   arrival_date_day_of_month       87396 non-null  int64
 7   stays_in_weekend_nights         87396 non-null  int64
 8   stays_in_week_nights            87396 non-null  int64
 9   adults                          87396 non-null  int64
 10  children                        87392 non-null  float64
 11  babies                          87396 non-null  int64
 12  meal                            87396 non-null  object
 13  country                         86944 non-null  object
 14  market_segment                  87396 non-null  object
 15  distribution_channel            87396 non-null  object
 16  is_repeated_guest               87396 non-null  int64
 17  previous_cancellations          87396 non-null  int64
 18  previous_bookings_not_canceled  87396 non-null  int64
 19  reserved_room_type              87396 non-null  object
 20  assigned_room_type              87396 non-null  object
 21  booking_changes                 87396 non-null  int64
 22  deposit_type                    87396 non-null  object
 23  agent                           75203 non-null  float64
 24  company                         5259 non-null   float64
 25  days_in_waiting_list            87396 non-null  int64
 26  customer_type                   87396 non-null  object
 27  adr                             87396 non-null  float64
 28  required_car_parking_spaces     87396 non-null  int64
 29  total_of_special_requests       87396 non-null  int64
 30  reservation_status              87396 non-null  object
 31  reservation_status_date         87396 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 22.0+ MB

#Cek Missing Values

In [ ]:
df.isnull().sum()

hotel                                 0
is_canceled                           0
lead_time                             0
arrival_date_year                     0
arrival_date_month                    0
arrival_date_week_number              0
arrival_date_day_of_month             0
stays_in_weekend_nights               0
stays_in_week_nights                  0
adults                                0
children                              4
babies                                0
meal                                  0
country                             452
market_segment                        0
distribution_channel                  0
is_repeated_guest                     0
previous_cancellations                0
previous_bookings_not_canceled        0
reserved_room_type                    0
assigned_room_type                    0
booking_changes                       0
deposit_type                          0
agent                             12193
company                           82137
days_in_waiting_list                  0
customer_type                         0
adr                                   0
required_car_parking_spaces           0
total_of_special_requests             0
reservation_status                    0
reservation_status_date               0
dtype: int64

#Data Cleaning

##Salin Dataset

In [ ]:
clean_df = df.copy()

NameError: name 'df' is not defined

In [ ]:
df['children'] = df['children'].fillna(df['children'].mode()[0])
df['country'] = df['country'].fillna(df['country'].mode()[0])
df.drop(['agent'], axis=1, inplace=True)
df.drop(['company'], axis=1, inplace=True)

# Ganti Tipe Data

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 87396 entries, 0 to 119389
Data columns (total 30 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           87396 non-null  object
 1   is_canceled                     87396 non-null  int64
 2   lead_time                       87396 non-null  int64
 3   arrival_date_year               87396 non-null  int64
 4   arrival_date_month              87396 non-null  object
 5   arrival_date_week_number        87396 non-null  int64
 6   arrival_date_day_of_month       87396 non-null  int64
 7   stays_in_weekend_nights         87396 non-null  int64
 8   stays_in_week_nights            87396 non-null  int64
 9   adults                          87396 non-null  int64
 10  children                        87396 non-null  float64
 11  babies                          87396 non-null  int64
 12  meal                            87396 non-null  object
 13  country                         87396 non-null  object
 14  market_segment                  87396 non-null  object
 15  distribution_channel            87396 non-null  object
 16  is_repeated_guest               87396 non-null  int64
 17  previous_cancellations          87396 non-null  int64
 18  previous_bookings_not_canceled  87396 non-null  int64
 19  reserved_room_type              87396 non-null  object
 20  assigned_room_type              87396 non-null  object
 21  booking_changes                 87396 non-null  int64
 22  deposit_type                    87396 non-null  object
 23  days_in_waiting_list            87396 non-null  int64
 24  customer_type                   87396 non-null  object
 25  adr                             87396 non-null  float64
 26  required_car_parking_spaces     87396 non-null  int64
 27  total_of_special_requests       87396 non-null  int64
 28  reservation_status              87396 non-null  object
 29  reservation_status_date         87396 non-null  object
dtypes: float64(2), int64(16), object(12)
memory usage: 20.7+ MB

In [ ]:
#df['children'] = df['children'].fillna(0).astype('int64')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 87396 entries, 0 to 119389
Data columns (total 30 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           87396 non-null  object
 1   is_canceled                     87396 non-null  int64
 2   lead_time                       87396 non-null  int64
 3   arrival_date_year               87396 non-null  int64
 4   arrival_date_month              87396 non-null  object
 5   arrival_date_week_number        87396 non-null  int64
 6   arrival_date_day_of_month       87396 non-null  int64
 7   stays_in_weekend_nights         87396 non-null  int64
 8   stays_in_week_nights            87396 non-null  int64
 9   adults                          87396 non-null  int64
 10  children                        87396 non-null  int64
 11  babies                          87396 non-null  int64
 12  meal                            87396 non-null  object
 13  country                         87396 non-null  object
 14  market_segment                  87396 non-null  object
 15  distribution_channel            87396 non-null  object
 16  is_repeated_guest               87396 non-null  int64
 17  previous_cancellations          87396 non-null  int64
 18  previous_bookings_not_canceled  87396 non-null  int64
 19  reserved_room_type              87396 non-null  object
 20  assigned_room_type              87396 non-null  object
 21  booking_changes                 87396 non-null  int64
 22  deposit_type                    87396 non-null  object
 23  days_in_waiting_list            87396 non-null  int64
 24  customer_type                   87396 non-null  object
 25  adr                             87396 non-null  float64
 26  required_car_parking_spaces     87396 non-null  int64
 27  total_of_special_requests       87396 non-null  int64
 28  reservation_status              87396 non-null  object
 29  reservation_status_date         87396 non-null  object
dtypes: float64(1), int64(17), object(12)
memory usage: 20.7+ MB

#Insight

## Pembatalan Berdasarkan Lead Time

## Pembatalan Berdasarkan Deposit

## Pembatalan Berdasarkan Segmen Pasar

## Pembatalan Berdasarkan Distribusi Chanel

##Pembatalan Berdasarkan ADR