#HOTEL BOOKING DEMAND

Dataset akan dilakukan dilakukan:
1. Cek Data Duplikat
2. Menghapus Data Duplikat
3. Cek Missing Value
4. Membersikan Nilai Tidak Valid
5. Mengganti Tipe Data
6. Menghapus Outlier ADR
7. Menambahkan Engineering Feature

# Import Data

In [1]:
import pandas as pd
import numpy as np

#Load Data dari Github

In [2]:
# Membaca dataset hotel booking demand dari GitHub

df = pd.read_csv("https://raw.githubusercontent.com/hastisf/python-data-analyst/refs/heads/master/hotel_bookings.csv")

In [3]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

# Import Library & Install

Menginstall library seperti koneksi database, pengolahan data, dan visualisasi

In [47]:
# Install Library

!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.49)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.12)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)

Memanggil library agar bisa digunakan dalan program

In [48]:
from sqlalchemy import create_engine

# Informasi Dataset

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB

#Describe Data

In [7]:
df.describe()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119386.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,103050.000000,6797.000000,119390.000000,119390.000000,119390.000000,119390.000000
mean,0.370416,104.011416,2016.156554,27.165173,15.798241,0.927599,2.500302,1.856403,0.103890,0.007949,0.031912,0.087118,0.137097,0.221124,86.693382,189.266735,2.321149,101.831122,0.062518,0.571363
std,0.482918,106.863097,0.707476,13.605138,8.780829,0.998613,1.908286,0.579261,0.398561,0.097436,0.175767,0.844336,1.497437,0.652306,110.774548,131.655015,17.594721,50.535790,0.245291,0.792798
min,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6.000000,0.000000,-6.380000,0.000000,0.000000
25%,0.000000,18.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,62.000000,0.000000,69.290000,0.000000,0.000000
50%,0.000000,69.000000,2016.000000,28.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,179.000000,0.000000,94.575000,0.000000,0.000000
75%,1.000000,160.000000,2017.000000,38.000000,23.000000,2.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,229.000000,270.000000,0.000000,126.000000,0.000000,1.000000
max,1.000000,737.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,55.000000,10.000000,10.000000,1.000000,26.000000,72.000000,21.000000,535.000000,543.000000,391.000000,5400.000000,8.000000,5.000000

#Data Cleaning

## Salin Dataset

In [8]:
# Salin Dataset untuk mempertahankan Data Asli

clean_df = df.copy()

## Cek Missing Values

In [9]:
# Cek Apakah Ada Missing Values

clean_df.isnull()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,True,True,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
119386,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
119387,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
119388,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
119389,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False

In [10]:
# Cek Jumlah Missing Value

clean_df.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

## Handle Missing Value

In [11]:
# Isi children kosong dengan modus karena mean = modus = 1
clean_df['children'] = clean_df['children'].fillna(
    clean_df['country'].mode()[0])

# Isi country kosong dengan negara terbanyak karena tipe data object
clean_df['country'] = clean_df['country'].fillna(
    clean_df['country'].mode()[0])

# Isi agent kosong dengan 0
clean_df['agent'] = clean_df['agent'].fillna(0)

# Drop kolom company karena >94% data berisi NULL
clean_df.drop(['company'], axis=1, inplace=True)

# Isi meal undefined dengan modus
clean_df['meal'] = clean_df['meal'].replace(
    'Undefined', 'unknown')

## Hapus Angka Tidak Valid

In [12]:
# Menghapus data adr yang negatif
clean_df = clean_df[clean_df['adr'] >= 0]

# Menghapus jumlah tamu adults negatif
clean_df = clean_df[
    clean_df['adults'] >= 0]

# Menghapus jumlah tamu children negatif
# clean_df = clean_df[clean_df['children'] >= 0]
# run kembali setelah ubah data type

# Menghapus jumlah tamu babies negatif
clean_df = clean_df[
    clean_df['babies'] >= 0]

## Hapus Outlier ADR

In [13]:
# Mengambil nilai persentil 99 dari kolom adr
q99 = clean_df['adr'].quantile(0.99)

# Menghapus nilai adr yang terlalu tinggi (outlier 1%)
clean_df = clean_df[
    clean_df['adr'] <= q99]

## Ubah Tipe Data

In [14]:
# Melihat Tipe Data Awal

clean_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 118221 entries, 0 to 119389
Data columns (total 31 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           118221 non-null  object
 1   is_canceled                     118221 non-null  int64
 2   lead_time                       118221 non-null  int64
 3   arrival_date_year               118221 non-null  int64
 4   arrival_date_month              118221 non-null  object
 5   arrival_date_week_number        118221 non-null  int64
 6   arrival_date_day_of_month       118221 non-null  int64
 7   stays_in_weekend_nights         118221 non-null  int64
 8   stays_in_week_nights            118221 non-null  int64
 9   adults                          118221 non-null  int64
 10  children                        118221 non-null  object
 11  babies                          118221 non-null  int64
 12  meal                            118221 non-null  object
 13  country                         118221 non-null  object
 14  market_segment                  118221 non-null  object
 15  distribution_channel            118221 non-null  object
 16  is_repeated_guest               118221 non-null  int64
 17  previous_cancellations          118221 non-null  int64
 18  previous_bookings_not_canceled  118221 non-null  int64
 19  reserved_room_type              118221 non-null  object
 20  assigned_room_type              118221 non-null  object
 21  booking_changes                 118221 non-null  int64
 22  deposit_type                    118221 non-null  object
 23  agent                           118221 non-null  float64
 24  days_in_waiting_list            118221 non-null  int64
 25  customer_type                   118221 non-null  object
 26  adr                             118221 non-null  float64
 27  required_car_parking_spaces     118221 non-null  int64
 28  total_of_special_requests       118221 non-null  int64
 29  reservation_status              118221 non-null  object
 30  reservation_status_date         118221 non-null  object
dtypes: float64(2), int64(16), object(13)
memory usage: 28.9+ MB

In [15]:
# Mengubah Tipe Data dari float64 ke int64

# clean_df['children'] = clean_df['children'].fillna(0).astype('int64')
# gagal run karena mungkin ada data NaN atau tanpa angka

# data aneh/non-angka otomatis dijadikan NaN -> diisi 0 -> int64
clean_df['children'] = pd.to_numeric(clean_df['children'],
    errors='coerce').fillna(0).astype('int64')

# Mengubah Tipe Data dari float64 ke int64 agar konsisten
clean_df['agent'] = clean_df['agent'].fillna(0).astype('int64')

# Mengubah Tipe Data dari Object ke Datetime
clean_df['reservation_status_date'] = pd.to_datetime(
    clean_df['reservation_status_date'])

In [16]:
# Melihat Data setelah Diubah Tipe Data

clean_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 118221 entries, 0 to 119389
Data columns (total 31 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           118221 non-null  object
 1   is_canceled                     118221 non-null  int64
 2   lead_time                       118221 non-null  int64
 3   arrival_date_year               118221 non-null  int64
 4   arrival_date_month              118221 non-null  object
 5   arrival_date_week_number        118221 non-null  int64
 6   arrival_date_day_of_month       118221 non-null  int64
 7   stays_in_weekend_nights         118221 non-null  int64
 8   stays_in_week_nights            118221 non-null  int64
 9   adults                          118221 non-null  int64
 10  children                        118221 non-null  int64
 11  babies                          118221 non-null  int64
 12  meal                            118221 non-null  object
 13  country                         118221 non-null  object
 14  market_segment                  118221 non-null  object
 15  distribution_channel            118221 non-null  object
 16  is_repeated_guest               118221 non-null  int64
 17  previous_cancellations          118221 non-null  int64
 18  previous_bookings_not_canceled  118221 non-null  int64
 19  reserved_room_type              118221 non-null  object
 20  assigned_room_type              118221 non-null  object
 21  booking_changes                 118221 non-null  int64
 22  deposit_type                    118221 non-null  object
 23  agent                           118221 non-null  int64
 24  days_in_waiting_list            118221 non-null  int64
 25  customer_type                   118221 non-null  object
 26  adr                             118221 non-null  float64
 27  required_car_parking_spaces     118221 non-null  int64
 28  total_of_special_requests       118221 non-null  int64
 29  reservation_status              118221 non-null  object
 30  reservation_status_date         118221 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(18), object(11)
memory usage: 28.9+ MB

In [17]:
# Menghapus jumlah tamu children negatif

clean_df = clean_df[clean_df['children'] >= 0]

## Merapikan Data

In [18]:
# Menghilangkan Spasi Berlebih
# Mengganti Spasi Antar Kata dengan _
# Data Dibuat Lower

clean_df['hotel'] = clean_df['hotel'].str.strip().str.lower().str.replace(' ', '_')
clean_df['arrival_date_month'] = clean_df['arrival_date_month'].str.strip().str.lower().str.replace(' ', '_')
clean_df['meal'] = clean_df['meal'].str.strip().str.lower().str.replace(' ', '_')
clean_df['country'] = clean_df['country'].str.strip().str.lower().str.replace(' ', '_')
clean_df['market_segment'] = clean_df['market_segment'].str.strip().str.lower().str.replace(' ', '_')
clean_df['distribution_channel'] = clean_df['distribution_channel'].str.strip().str.lower().str.replace(' ', '_')
clean_df['reserved_room_type'] = clean_df['reserved_room_type'].str.strip().str.lower().str.replace(' ', '_')
clean_df['assigned_room_type'] = clean_df['assigned_room_type'].str.strip().str.lower().str.replace(' ', '_')
clean_df['deposit_type'] = clean_df['deposit_type'].str.strip().str.lower().str.replace(' ', '_')
clean_df['customer_type'] = clean_df['customer_type'].str.strip().str.lower().str.replace(' ', '_')
clean_df['reservation_status'] = clean_df['reservation_status'].str.strip().str.lower().str.replace(' ', '_')

In [19]:
# Cek Data yang Sudah Dirapikan

clean_df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,resort_hotel,0,342,2015,july,27,1,0,0,2,...,3,no_deposit,0,0,transient,0.0,0,0,check-out,2015-07-01
1,resort_hotel,0,737,2015,july,27,1,0,0,2,...,4,no_deposit,0,0,transient,0.0,0,0,check-out,2015-07-01
2,resort_hotel,0,7,2015,july,27,1,0,1,1,...,0,no_deposit,0,0,transient,75.0,0,0,check-out,2015-07-02
3,resort_hotel,0,13,2015,july,27,1,0,1,1,...,0,no_deposit,304,0,transient,75.0,0,0,check-out,2015-07-02
4,resort_hotel,0,14,2015,july,27,1,0,2,2,...,0,no_deposit,240,0,transient,98.0,0,1,check-out,2015-07-03

## Cek Data Duplikat

In [20]:
clean_df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
119385    False
119386    False
119387    False
119388    False
119389    False
Length: 118221, dtype: bool

In [21]:
# Menjumlahkan Data Duplikat

clean_df.duplicated().sum()

np.int64(31995)

## Hapus Data Duplikat

In [22]:
# Menghapus data duplikat

clean_df.drop_duplicates(inplace=True)

In [24]:
# Cek Jumlah Data Duplikat (Harusnya np.int64(0))

clean_df.duplicated().sum()

np.int64(0)

# Klasifikasi ADR

In [25]:
clean_df['adr']

0           0.00
1           0.00
2          75.00
3          75.00
4          98.00
           ...
119385     96.14
119386    225.43
119387    157.71
119388    104.40
119389    151.20
Name: adr, Length: 86226, dtype: float64

In [26]:
# Mengetahui Sebaran Nilai ADR

pd.DataFrame({
'max' : [clean_df['adr'].max()],
'min' : [clean_df['adr'].min()],
'mode' : [clean_df['adr'].mode()[0]],
'median' : [clean_df['adr'].median()],
'mean' : [clean_df['adr'].mean()]
})

     max  min  mode  median        mean
0  252.0  0.0   0.0    97.7  103.918703

In [27]:
# Agar Nilai Absolut

clean_df['adr'] = clean_df['adr'].abs()

#Klasifikasi ADR

def adrcategory(adr):

  if adr == 0:
    return 'free'

  elif 1 <= adr <= 75:
    return 'low'

  elif 76 <= adr <= 150:
    return 'high'

  else:
    return 'premium'

# Membuat Kolom Baru adr_category

In [28]:
# Membuat Kolom adr_category Berdasarkan adr

clean_df['adr_category'] = (df['adr'].apply(adrcategory))

In [29]:
# Menampilkan adr dan adr_category

clean_df[['adr','adr_category']].head()

    adr adr_category
0   0.0         free
1   0.0         free
2  75.0          low
3  75.0          low
4  98.0         high

In [30]:
# Menampilkan Tabel

clean_df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,adr_category
0,resort_hotel,0,342,2015,july,27,1,0,0,2,...,no_deposit,0,0,transient,0.0,0,0,check-out,2015-07-01,free
1,resort_hotel,0,737,2015,july,27,1,0,0,2,...,no_deposit,0,0,transient,0.0,0,0,check-out,2015-07-01,free
2,resort_hotel,0,7,2015,july,27,1,0,1,1,...,no_deposit,0,0,transient,75.0,0,0,check-out,2015-07-02,low
3,resort_hotel,0,13,2015,july,27,1,0,1,1,...,no_deposit,304,0,transient,75.0,0,0,check-out,2015-07-02,low
4,resort_hotel,0,14,2015,july,27,1,0,2,2,...,no_deposit,240,0,transient,98.0,0,1,check-out,2015-07-03,high

# Validasi Data Setelah Cleaning

In [31]:
# Memastikan Dataset Sudah Bersih

print("\nMissing Value Setelah Cleaning")
print(clean_df.isnull().sum())

print("\nJumlah Duplikat Setelah Cleaning")
print(clean_df.duplicated().sum())

print("\nStatistik Setelah Cleaning")
print(clean_df.describe())

Missing Value Setelah Cleaning
hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
agent                             0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
reservation_status_date           0
adr_category                      0
dtype: int64

Jumlah Duplikat Setelah Cleaning
0

Statistik Setelah Cleaning
        is_canceled     lead_time  arrival_date_year  \
count  86226.000000  86226.000000       86226.000000
mean       0.273757     80.041264        2016.204869
min        0.000000      0.000000        2015.000000
25%        0.000000     11.000000        2016.000000
50%        0.000000     49.000000        2016.000000
75%        1.000000    125.000000        2017.000000
max        1.000000    737.000000        2017.000000
std        0.445889     86.235661           0.686126

       arrival_date_week_number  arrival_date_day_of_month  \
count              86226.000000               86226.000000
mean                  26.783186                  15.802391
min                    1.000000                   1.000000
25%                   16.000000                   8.000000
50%                   27.000000                  16.000000
75%                   37.000000                  23.000000
max                   53.000000                  31.000000
std                   13.733321                   8.837704

       stays_in_weekend_nights  stays_in_week_nights        adults  \
count             86226.000000          86226.000000  86226.000000
mean                  1.003050              2.620381      1.871315
min                   0.000000              0.000000      0.000000
25%                   0.000000              1.000000      2.000000
50%                   1.000000              2.000000      2.000000
75%                   2.000000              4.000000      2.000000
max                  19.000000             50.000000     55.000000
std                   1.032553              2.055747      0.626635

           children        babies  is_repeated_guest  previous_cancellations  \
count  86226.000000  86226.000000       86226.000000            86226.000000
mean       0.127143      0.010646           0.039362                0.030803
min        0.000000      0.000000           0.000000                0.000000
25%        0.000000      0.000000           0.000000                0.000000
50%        0.000000      0.000000           0.000000                0.000000
75%        0.000000      0.000000           0.000000                0.000000
max       10.000000     10.000000           1.000000               26.000000
std        0.434803      0.112960           0.194455                0.371595

       previous_bookings_not_canceled  booking_changes         agent  \
count                    86226.000000     86226.000000  86226.000000
mean                         0.186092         0.269501     79.885962
min                          0.000000         0.000000      0.000000
25%                          0.000000         0.000000      9.000000
50%                          0.000000         0.000000      9.000000
75%                          0.000000         0.000000    201.000000
max                         72.000000        21.000000    535.000000
std                          1.743180         0.724210    109.493174

       days_in_waiting_list           adr  required_car_parking_spaces  \
count          86226.000000  86226.000000                 86226.000000
mean               0.756338    103.918703                     0.082724
min                0.000000      0.000000                     0.000000
25%                0.000000     72.000000                     0.000000
50%                0.000000     97.700000                     0.000000
75%                0.000000    131.700000                     0.000000
max              391.000000    252.000000                     8.000000
std               10.067080     47.936931                     0.279272

       total_of_special_requests        reservation_status_date
count               86226.000000                          86226
mean                    0.696066  2016-08-28 20:02:59.361213440
min                     0.000000            2014-10-17 00:00:00
25%                     0.000000            2016-03-16 00:00:00
50%                     0.000000            2016-09-06 00:00:00
75%                     1.000000            2017-03-02 00:00:00
max                     5.000000            2017-09-14 00:00:00
std                     0.829087                            NaN

In [32]:
clean_df[clean_df.duplicated()]

Empty DataFrame
Columns: [hotel, is_canceled, lead_time, arrival_date_year, arrival_date_month, arrival_date_week_number, arrival_date_day_of_month, stays_in_weekend_nights, stays_in_week_nights, adults, children, babies, meal, country, market_segment, distribution_channel, is_repeated_guest, previous_cancellations, previous_bookings_not_canceled, reserved_room_type, assigned_room_type, booking_changes, deposit_type, agent, days_in_waiting_list, customer_type, adr, required_car_parking_spaces, total_of_special_requests, reservation_status, reservation_status_date, adr_category]
Index: []

[0 rows x 32 columns]

In [33]:
# Total malam menginap
clean_df['total_nights'] = (
    clean_df['stays_in_weekend_nights'] +
    clean_df['stays_in_week_nights'])

# Total tamu
clean_df['total_guest'] = (
    clean_df['adults'] +
    clean_df['children'] +
    clean_df['babies'])

# Total histori booking pelanggan
clean_df['customer_history'] = (
    clean_df['previous_bookings_not_canceled'] +
    clean_df['previous_cancellations'])

# Menghapus booking tanpa tamu.
clean_df = clean_df[
    clean_df['total_guest'] > 0]

#Insight

## 1. Pembatalan Berdasarkan Tipe Deposit

In [34]:
total_pesanan = clean_df.groupby('deposit_type')['is_canceled'].count()
total_batal = clean_df.groupby('deposit_type')['is_canceled'].sum()
persen_batal = (total_batal/total_pesanan*100).round(2)

tabel_deposit = pd.DataFrame({
    'total_pesanan': total_pesanan,
    'total_batal': total_batal,
    'persen_batal': persen_batal})

tabel_deposit = tabel_deposit.sort_values(by='persen_batal', ascending=False)

print(tabel_deposit)

              total_pesanan  total_batal  persen_batal
deposit_type
non_refund             1036          981         94.69
no_deposit            84917        22582         26.59
refundable              107           26         24.30

## 2. Total Tamu Menginap Berdasarkan arrival_date_month

In [35]:
total_tamu = (clean_df[clean_df['is_canceled'] == 0].groupby
 (['hotel','arrival_date_month'])['is_canceled'].count())

rata_rata_harga_kamar = (clean_df[clean_df['is_canceled']==0].groupby
      (['hotel','arrival_date_month'])['adr'].mean().round(2))

total_tamu_by_month = pd.DataFrame({
    'total_tamu': total_tamu,
    'rata_rata_harga_kamar': rata_rata_harga_kamar})

total_tamu_by_month = total_tamu_by_month.sort_values(
    by='rata_rata_harga_kamar', ascending=False).head(20)

print(total_tamu_by_month)

                                 total_tamu  rata_rata_harga_kamar
hotel        arrival_date_month
resort_hotel august                    2782                 168.14
             july                      2885                 144.93
city_hotel   may                       3624                 123.45
             august                    4411                 120.87
             june                      3458                 119.78
             july                      3797                 118.47
             september                 3156                 116.51
             april                     3301                 113.07
resort_hotel june                      1917                 108.26
city_hotel   october                   3067                 105.35
resort_hotel september                 1873                  98.66
city_hotel   march                     3467                  91.20
             december                  2011                  89.88
             november                  2176                  88.19
             february                  2612                  87.79
             january                   1960                  83.28
resort_hotel may                       2246                  77.73
             april                     2166                  76.77
             october                   2207                  62.66
             december                  1695                  61.27

## 3. Top 5 Rank Tamu Berdasarkan Negara Asal

In [36]:
asal_negara = (
    clean_df[clean_df['is_canceled'] == 0]
    .groupby('country')['is_canceled']
    .count())

top_rank_negara = pd.DataFrame({
    'total_tamu': asal_negara
})

top_rank_negara = top_rank_negara.sort_values(by='total_tamu',
ascending=False).head(5)

print(top_rank_negara)

         total_tamu
country
prt           17707
gbr            8398
fra            7043
esp            5213
deu            4317

## 4. Total Special Request Berdasarkan Market Segment

In [37]:
special_request = (clean_df[clean_df['is_canceled'] ==0].groupby
 ('market_segment')['total_of_special_requests'].mean().round(2))

top_market_segment = pd.DataFrame({
    'rata_rata_special_request': special_request})

top_market_segment= top_market_segment.sort_values(by='rata_rata_special_request',
ascending=False).head()

print(top_market_segment)

                rata_rata_special_request
market_segment
online_ta                            1.05
complementary                        1.00
direct                               0.59
offline_ta/to                        0.37
corporate                            0.29

## 5. Jumlah Pesanan Berdasarkan Perubahan Pesanan

In [38]:
booking_changes = (clean_df.groupby('booking_changes').size().index)

total_pesanan = (clean_df.groupby('booking_changes')['is_canceled'].size())

total_batal = (clean_df.groupby('booking_changes')['is_canceled'].sum())

summary = pd.DataFrame({
    'booking_changes': booking_changes,
    'total_pesanan': total_pesanan.values,
    'total_batal': total_batal.values})

summary = summary.sort_values(
    by='booking_changes',
    ascending=True).head()

print(summary)

   booking_changes  total_pesanan  total_batal
0                0          70572        21200
1                1          10652         1463
2                2           3426          691
3                3            836          124
4                4            338           63

## 6. Jumlah Tipe Pesanan Makanan Berdasarkan Hotel

In [39]:
tipe_paket_makan = (clean_df[clean_df['is_canceled'] == 0].groupby
 (['hotel','meal'])['is_canceled'].count())

total_meal_dipesan = pd.DataFrame({
    'total_dipesan': tipe_paket_makan})

top_meal_dipesan = total_meal_dipesan.sort_values(
    by=['hotel', 'total_dipesan'],
    ascending=[True, False])

print(top_meal_dipesan)

                      total_dipesan
hotel        meal
city_hotel   bb               29143
             sc                5982
             hb                1906
             fb                   9
resort_hotel bb               20326
             hb                4413
             unknown            394
             fb                 225
             sc                  73

## 7. Total Pesanan Berdasarkan Agent

In [44]:
total_agen_pesan = (clean_df[clean_df['agent'] !=0].groupby('agent')
['is_canceled'].count())

total_agen_batal = (clean_df[clean_df['agent'] !=0].groupby('agent')
['is_canceled'].sum())

agen_batal = pd.DataFrame({
    'total_agen_pesan': total_agen_pesan,
    'total_agen_batal': total_agen_batal})

agen_batal = agen_batal.sort_values(by='total_agen_batal',
    ascending=False).head()

print(agen_batal)

       total_agen_pesan  total_agen_batal
agent
9                 28614             11483
240               12505              4700
14                 3260               564
1                  1228               457
250                2607               455

# Koneksi Database Supabase

In [49]:
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

url = URL.create(
    drivername="postgresql",
    username="postgres.aihxmxreabuakdiqclef",
    password="*Hastinafis150226",
    host="aws-1-ap-southeast-1.pooler.supabase.com",
    port=6543,
    database="postgres",
    query={"sslmode": "require"})

engine = create_engine(url)

#DB_URL = "postgresql://postgres.aihxmxreabuakdiqclef:*Hastinafis150226@aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require"

#engine = create_engine(DB_URL)

In [50]:
from sqlalchemy import text

with engine.connect() as conn:
    print(conn.execute(text("SELECT 1")).fetchone())

(1,)

# Simpan ke Database

In [51]:
# Dataset akan dikirim ke PostgreSQL di Dbeaver

clean_df.to_sql(
    'hotel_bookings',
    engine,
    if_exists='replace',
    index=False,
    chunksize=100,
    method=None
)

#clean_df.to_sql("hotel_bookings", engine, if_exists="replace", index=False)

86060